--- #YAML:1.0
name:               XML-Compile-SOAP-AnyEvent
version:            0.01
abstract:           SOAP with AnyEvent
author:
    - Aleksey Mashanov/Mark Overmeer
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    AnyEvent::HTTP:      1.46
    Log::Report:         0.28
    Time::HiRes:         0
    XML::Compile::SOAP:  2.18
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
